### ISSUE TITLE
Cannot load module "PyhtmlTemplate".

### ISSUE THREAD

**Issue by ChrisBPhlox** [jczic/MicroWebSrv2#29]
Hi,

I tried to use the MicroWebSrv2 on my esp32 with the main.py on the MicroWebSrv2-master directory and I get this error 

>  File "main.py", line 148, in <module>
  File "MicroWebSrv2/microWebSrv2.py", line 136, in LoadModule
MicroWebSrv2Exception: Cannot load module "PyhtmlTemplate".

> 
I am using uPyCraft and I can see the file inside the mods directory.
I don't understand why it can't load it?

Thanks

Chris

**Comment by jczic** [comment]
Hello @ChrisBPhlox,
Yes I know that, this is a limited memory problem.

If you put the MicroWebSrv2 sources in the flash memory, your microcontroller must have more RAM (example with ESP32 modules with 4MB of SPIRAM).

Otherwise, you must to put MicroWebSrv2 sources in the dedicated modules folder of the MicroPython port before compile the firmware. In this case, `.py` files will be compiled/integrated directly in the firmware with a greatly reduced memory usage.

It's ok for you?

**Comment by jczic** [comment]
(Check issue https://github.com/jczic/MicroWebSrv2/issues/21)

**Comment by ChrisBPhlox** [comment]
Bonjour,

Je m’en doutais un peu mais je suis nouveau sur ESP32 et µpython, j’ai toujours utilisé des pic jusqu’à présent.
Je suppose qu’on peut trouver des tutos sur le sujet.
Bravo pour le travail effectué

Merci

Christophe Blanc

**Comment by jczic** [comment]
Merci :)
Oui il y en a beaucoup en effet. Un ESP32 avec 4Mo de SPIRAM en extension est conseillé pour bien s'amuser.
Bon courage!
